services:
  - type: web
    name: crag-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run chainlit_app.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TOKENIZERS_PARALLELISM
        value: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BRAVE_API_KEY
        sync: false
